# Generated by Django 5.0.6 on 2024-05-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_item_category_item_category_alter_item_labels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(default='customer@gmail.com', max_length=254)),
                ('location', models.CharField(default='Dar es salaam', max_length=200)),
                ('picture', models.ImageField(default='default.jpg', upload_to='static/images/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
