# Generated by Django 5.0.6 on 2024-05-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_date_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecturalproduct',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='buildingsupply',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='constructionequipment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='slug',
        ),
    ]
