# Generated by Django 5.0.6 on 2024-06-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_architecturalproduct_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('confirmed', 'Order Confirmation'), ('shipped', 'Order Shipment'), ('estimated_delivery', 'Estimated Delivery Time'), ('delivered', 'Delivery Update Feedback Request')], default='confirmed', max_length=20)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buildingsupply',
            name='category',
        ),
        migrations.RemoveField(
            model_name='constructionequipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='address',
            name='apartment_address',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='reference_code',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='refund_requested',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='item',
            name='likes',
        ),
        migrations.AddField(
            model_name='item',
            name='seller_name',
            field=models.CharField(default='john', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(max_length=1),
        ),
        migrations.DeleteModel(
            name='ArchitecturalProduct',
        ),
        migrations.DeleteModel(
            name='BuildingSupply',
        ),
        migrations.DeleteModel(
            name='ConstructionEquipment',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='RawMaterial',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
